keyseg_para = {
    "chengdu_large": {
        "seg_num": 107655,
        "time_delta": 3600,
        "d_seg": 64,
        "d_s": 2 * (64 + 0) + 64 + 3,
        "d_m7": 2048,
        "d_m8": 256,
        "dropout": 0.2,
        "epochs": 1000,
        "batch_size": 8192,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip":1.0,
        "use_node2vec": True,
        "use_traffic4key": True,
        "use_offset": True,
        "mask_size": 100,
        "utc": 8,
        "pretrained_input_emb_path": "segs_embedding_64.npy",
        "segs_geo": "segs_geo.npy",
        "traffic_popularity": "traffic_popularity.npy",
        "dam": "csm_all.txt",
    },
    "porto_large": {
        "seg_num": 185074,
        "time_delta": 3600,
        "d_seg": 64,
        "d_s": 2 * (64 + 0) + 64 + 3,
        "d_m7": 2048,
        "d_m8": 256,
        "dropout": 0.2,
        "epochs": 1000,
        "batch_size": 8192,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip": 1.0,
        "use_node2vec": True,
        "use_traffic4key": True,
        "use_offset": True,
        "mask_size": 100,
        "utc": 1,
        "pretrained_input_emb_path": "segs_embedding_64.npy",
        "segs_geo": "segs_geo.npy",
        "traffic_popularity": "traffic_popularity.npy",
        "dam": "csm_all.txt",
    },
    "beijing_large": {
        "seg_num": 311769,
        "time_delta": 3600,
        "d_seg": 64,
        "d_s": 2 * (64 + 0) + 64 + 3,
        "d_m7": 2048,
        "d_m8": 256,
        "dropout": 0.2,
        "epochs": 1000,
        "batch_size": 8192,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip": 1.0,
        "use_node2vec": True,
        "use_traffic4key": True,
        "use_offset": True,
        "mask_size": 100,
        "utc": 0,
        "pretrained_input_emb_path": "segs_embedding_64.npy",
        "segs_geo": "segs_geo.npy",
        "traffic_popularity": "traffic_popularity.npy",
        "dam": "csm_all.txt",
    },
    "xian_large": {
        "seg_num": 59927,
        "time_delta": 3600,
        "d_seg": 64,
        "d_s": 2 * (64 + 0) + 64 + 3,
        "d_m7": 2048,
        "d_m8": 256,
        "dropout": 0.2,
        "epochs": 1000,
        "batch_size": 8192,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip": 1.0,
        "use_node2vec": True,
        "use_traffic4key": True,
        "use_offset": True,
        "mask_size": 100,
        "utc": 8,
        "pretrained_input_emb_path": "segs_embedding_64.npy",
        "segs_geo": "segs_geo.npy",
        "traffic_popularity": "traffic_popularity.npy",
        "dam": "csm_all.txt",
    },
    "sanfran_large": {
        "seg_num": 26659,
        "time_delta": 3600,
        "d_seg": 64,
        "d_s": 2 * (64 + 0) + 64 + 3,
        "d_m7": 2048,
        "d_m8": 256,
        "dropout": 0.2,
        "epochs": 1000,
        "batch_size": 8192,
        "lr_base": 1e-3,
        "lr_step": 2,
        "lr_decay": 0.8,
        "clip": 1.0,
        "use_node2vec": True,
        "use_traffic4key": True,
        "use_offset": True,
        "mask_size": 100,
        "utc": -7,
        "pretrained_input_emb_path": "segs_embedding_64.npy",
        "segs_geo": "segs_geo.npy",
        "traffic_popularity": "traffic_popularity.npy",
        "dam": "csm_all.txt",
    },
}
